### ISSUE TITLE
undefined symbol: CRYPTO_free

### ISSUE THREAD

**Issue by Zeimyth** [eriktews/gensafeprime#2]
After installing the module using 'sudo python setup.py install', I opened the python command-line interpreter and tried 'import gensafeprime'. I got this error:

ImportError: /usr/local/lib/python2.7/dist-packages/gensafeprime.so: undefined symbol: CRYPTO_free

**Comment by runn1ng** [comment]
the same issue

**Comment by runn1ng** [comment]
Also using ubuntu, also having libssl-dev installed.

**Comment by runn1ng** [comment]
I installed your module from pip, but it does the same thing

**Comment by runn1ng** [comment]
I am new at this so sorry if I am writing nonsence

but when I point ldd at the built .so file like this

     ldd build/lib.linux-i686-2.7/gensafeprime.so

It doesn't show up ssl at all. Not sure where is any mistake.

**Comment by eriktews** [comment]
Let me install a ubuntu system as you use one. Which version are you running and are you on 32 or 64 bit?

**Comment by runn1ng** [comment]
It actually gets fixed by linking against "libcrypto" instead of (or in addition to) ssl.

I wrote it as a question on StackOverflow and someone recommended me that (more or less) and it seems to fix the issue.

All right.

http://stackoverflow.com/questions/27890155/cannot-install-a-python-module-written-in-c-that-links-openssl?noredirect=1#comment44184031_27890155

**Comment by runn1ng** [comment]
I can add it as a pull request if you want, it's really one word though

**Comment by eriktews** [comment]
Pull request has been merged to master, please try the new 1.3 release and see if you still have problems.
